Feature/22 making input keyword page
project-gemini-by-fluttter-univ/gemini-app pull request #40
Opened 2024-09-17 17:37 UTC by VisitSpace-com

<img width="369" alt="スクリーンショット 2024-09-18 2 31 47" src="https://github.com/user-attachments/assets/8fc27aa1-9695-434a-ad66-47e407c1a9c9">

キーワード入力画面を作成しました。

2024-09-17 23:07 UTC, Umigishi-Aoi requested changes
レイアウトいい感じです！

プルリクエスト名がブランチ名と同じになっているので修正をお願いします。

またコメントを確認の上修正をお願いします！

2024-09-17 23:07 UTC, Umigishi-Aoi commented on lib/presentation/keyword_input_page.dart
> +  }
`dispose`メソッドをoverrideしてこのメソッドの中でcontroller2個をdisposeしてください。

ここからはちょっと難しい話です。
上原さんの書き方の何がいけないのか、というのは前提知識が必要なので、できるだけ解説します。

`@override`はクラスの継承(`extends`)に関わるキーワードです。
継承元のクラスにあるメソッドを、継承後のクラスで使用する際、カスタマイズしたい、
そういう時に明示するキーワードだと思ってください。

具体例で言うと継承元の`State<KeywordInputPage>` には`dispose`という名前のメソッドがあり、このメソッドはStateの破棄時に呼び出されます。
（継承元で`dispose()`としている部分があります。）
Stateが破棄されるタイミングでcontrollerをdisposeしたい、となった時は、
継承元の`dispose`メソッドにdisposeの処理を追加するのが効率的です。
そんな時に使うのが`@override`のキーワードで、
継承元の`dispose`メソッドを継承後のクラスで再定義している、ということを明示します。
```dart
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
```

再定義するにあたり、継承元の`dispose`メソッドで行われる処理をコピペするのは面倒です。
これを解決するのが`super.dispose()`で、このメソッドで、継承元のメソッドの中身を実行してくれます。

上記理由から、上原さんの作成した`disposeController1() `は継承元に無いメソッドなので`@override`をつけるのはおかしく、
また、継承元で`disposeController1() `とされることもないため、
そもそもこのメソッドは呼び出されません。

上記をもとに、修正をお願いします。

2024-09-17 23:07 UTC, Umigishi-Aoi commented on lib/presentation/keyword_input_page.dart
> +                      // width: 480,
調整のためのコードが残ってしまっているので、
コメントアウトを解除するor`SizedBox`ごと削除する
をお願い致します。

2024-09-17 23:07 UTC, Umigishi-Aoi commented on lib/presentation/keyword_input_page.dart
> +                          labelText: 'お魚',
Figmaが適切でなかったかもです、申し訳ございません。

`hintText`でお願いします。

（文字の濃さがFigmaと変わってしまいますが、問題ありません。）

2024-09-17 23:07 UTC, Umigishi-Aoi commented on lib/presentation/keyword_input_page.dart
> +                      // width: 480,
上記コメントと同じ

2024-09-17 23:07 UTC, Umigishi-Aoi commented on lib/presentation/keyword_input_page.dart
> +                          labelText: '富士山',
上記と同じ

2024-09-18 11:45 UTC, VisitSpace-com commented
<img width="376" alt="（修正後）キーワード入力画面" src="https://github.com/user-attachments/assets/80027a54-b24e-4828-accb-f29f2f3af272">

2024-09-18 11:46 UTC, VisitSpace-com commented
修正しました！
・SizedBox 削除
・hintText に修正
・dispose()修正（←よく意味が分かっていません・・・）

2024-09-18 11:52 UTC, Umigishi-Aoi approved these changes
修正完璧です！

LGTM！

ブラウザ内のマージのボタンからマージしてください！

2024-09-18 12:15 UTC, merged